# Generated by Django 5.1 on 2024-08-08 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanchaModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('estado', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'canchas',
            },
        ),
        migrations.CreateModel(
            name='ReservaModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('nombre_cliente', models.CharField(max_length=200)),
                ('tiempo', models.IntegerField()),
                ('cancha_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.canchamodel')),
            ],
            options={
                'db_table': 'reservas',
            },
        ),
    ]
